events {
    worker_connections 1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;

    sendfile        on;
    keepalive_timeout  65;

    # =========================================================================
    # BIZLYTICS GATEWAY CONFIGURATION
    # =========================================================================

    server {
        listen       80;
        server_name  localhost;

        # 1. THE API GATEWAY (FastAPI)
        # All requests starting with /api/ go to the Python backend
        location / {
            proxy_pass http://backend:8000;
            
            # Critical: Forward the Multi-Tenant headers
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Tenant-ID $http_x_tenant_id;
        }

        # 2. THE MONITORING GATEWAY (Flower)
        # Allows  to see tasks via http://localhost/flower
        location /flower/ {
            proxy_pass http://flower:5555/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # Error Pages
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   html;
        }
    }
}
